### ISSUE TITLE
Unable to boot into system

### ISSUE THREAD

**Issue by reikdas** [dglt1/optimus-switch#1]
I removed optimus-manager before trying to install optimus-switch. (I disabled it from systemd and 
also cleared the config files)

I have the following output -

```
[reik@reik-msi ~]$ mhwd -li
> Installed PCI configs:
--------------------------------------------------------------------------------
                  NAME               VERSION          FREEDRIVER           TYPE
--------------------------------------------------------------------------------
           video-linux            2018.05.04                true            PCI
video-hybrid-intel-nvidia-bumblebee            2018.08.09               false            PCI


Warning: No installed USB configs!
```
I removed video-linux.
When trying to remove video-hybrid-intel-nvidia-bumblebee I was unable to because of conflicts with cuda, nvtop and python-pycuda.
I removed cuda, nvtop, python-pycuda, python-tensorflow-opt-cuda, python-pytorch-cuda, opencv-cuda and cudnn and was able to remove video-hybrid-intel-nvidia-bumblebee.
I installed video-nvidia.

I ran -
```
sudo pacman -S linux-headers acpi_call-dkms xf86-video-intel git (I chose linux419-headers)
sudo modprobe acpi_call
git clone https://github.com/dglt1/optimus-switch.git
sudo chmod +x ~/optimus-switch/install.sh
cd ~/optimus-switch
sudo ./install.sh
```
After reboot I get a flashing screen and I am unable to even boot into tty.

**Comment by dglt1** [comment]
as discussed on the manjaro forum [https://forum.manjaro.org/t/optimus-manager-alternative/76951/4](url)
this issue is likely because of conflicting video related .conf files in one of the following directories that should of been removed before installing optimus-switch:
/etc/X11/ 
/etc/X11/mhwd.d/
/etc/X11/xorg.conf.d/
/etc/modprobe.d/
/etc/modules-load.d/

you also did not remove bbswitch which can cause issues.  the only drivers required for optimus-switch are video-nvidia installed via MHWD and xf86-video-intel via pacman (if you dont want xf86-video-intel, there are instructions on how to use modesetting driver instead by uncommenting 1 line in set-intel.sh)
