### ISSUE TITLE
Multiple working acpi_calls when running gpu_switch_check.sh

### ISSUE THREAD

**Issue by nuk380y** [dglt1/optimus-switch#14]
As the title suggests, when I run `gpu_switch_check.sh` I see two (2) acpi_calls that return valid responses.

- `\_SB.PCI0.PEG0.PEGP._OFF`
- `\_SB.PCI0.PEG0.PEGP._DSM`

Going by context of the `switch/intel/no-optimus.sh` script, I'm guessing the correct acpi_call to use is the first one that ends in `_OFF`.

Is this correct, will either of the acpi_calls work, or should I use the `_DSM` acpi_call instead?  Either way, could this topic be expanded upon in the readme?

**Comment by samsapti** [comment]
You can use either of them, since they both work.

EDIT: `\_SB.PCI0.PEG0.PEGP._OFF` is the one I'm using.

**Comment by dglt1** [comment]
sometimes more than one can be detected but either one should should work, "\_SB.PCI0.PEG0.PEGP._OFF" just seems to be the most common.

no-optimus.sh was also just updated with @4n0nym0u53 's pull request which fixes an issue where waking from suspend in intel mode results in a black screen due to the nvidia card being removed from sysfs and thus failing to finish running the script. just hought i'd mention it if you wanted to edit yours to match

**Comment by nuk380y** [comment]
Thanks for the information!  Just wanted to make sure.  Already saw @4n0nym0u53's suggested fix in their thread and manually added it in to my local copy...should probably pull the update, though...

Either way, thank you!  Closing ticket.

**Comment by samsapti** [comment]
@nuk380y I just created a new pull request, because @dglt1 forgot to include the line to actually execute the acpi_call. Use that one instead.
