### ISSUE TITLE
Plz update instructions

### ISSUE THREAD

**Issue by SCCOBN** [dglt1/optimus-switch#23]
After half a dozen installs and lots of trial and error I got my setup working (ThinkPad W520, i7, Quatro 2000M) on Manjaro 20.

Instructions needs to be updated. In particular three issues. 

1) sudo pacman -S linuxXXX-headers acpi_call-dkms xorg-xrandr xf86-video-intel git
has to be modified to
sudo pacman -S linuxXXX-headers linuxXXX-acpi_call xorg-xrandr xf86-video-intel git
in my case
linux56-headers & linux56-acpi_call // dkms acpi_call does not work and if you google for it, forums scream at you for using dkms when there is kernel specific acpi_call exists. 

2) In your video driver section make two changes, first of all explicitly say to remove all video drivers, INCLUDING linux-video, secondly explicitly state to use video-nvidia-XXXxx and not video-hybrid-intel-nvidia-XXXxx-bumblebee...

3) Make it explicit that sudo /etc/switch/gpu_switch_check.sh step needs to be executed and file no-optimus.sh modified before set-intel.sh can be used successfully.

These scripts + clear instructions = excellent recipe for NVIDIA Optimus and Manjaro for newbs. Much easier to setup than optimus-manager (on which I gave up).

**Comment by dglt1** [comment]
> After half a dozen installs and lots of trial and error I got my setup working (ThinkPad W520, i7, Quatro 2000M) on Manjaro 20.
> 
> Instructions needs to be updated. In particular three issues.
> 
> 1. sudo pacman -S linuxXXX-headers acpi_call-dkms xorg-xrandr xf86-video-intel git
>    has to be modified to
>    sudo pacman -S linuxXXX-headers linuxXXX-acpi_call xorg-xrandr xf86-video-intel git
>    in my case
>    linux56-headers & linux56-acpi_call // dkms acpi_call does not work and if you google for it,
>    forums scream at you for using dkms when there is kernel specific acpi_call exists.

there are more kernels out there aside from manjaro's, i have acpi_call-dkms installed on arch 5.6 and arch-zen 5.6 and both build acpi_call modules just fine with dkms.

> 2. In your video driver section make two changes, first of all explicitly say to remove all video drivers, INCLUDING linux-video, secondly explicitly state to use video-nvidia-XXXxx and not video-hybrid-intel-nvidia-XXXxx-bumblebee...

the instructions do tell you to remove all other video drivers before continuing and tell you which drivers to install, the nvidia-hybrid-intel-blahblah drivers are not suggested nor can i understand why they would be mistaken for one another? one is video-nvidia-440xx and the other is not.

> 3. Make it explicit that sudo /etc/switch/gpu_switch_check.sh step needs to be executed and file no-optimus.sh modified before set-intel.sh can be used successfully.

no, that gpu_switch_check script needs to **run from intel mode or it will cause lockups as stated in the directions**

> 
> These scripts + clear instructions = excellent recipe for NVIDIA Optimus and Manjaro for newbs. Much easier to setup than optimus-manager (on which I gave up).

since it seems you have taken care of your issue, im gonna close this for now.
