### ISSUE TITLE
nvidia mode failed to start

### ISSUE THREAD

**Issue by salvianreynaldi** [dglt1/optimus-switch#3]
environment: manjaro fresh install, with Nvidia mx250 (acer swift 3)

after running set-nvidia and reboot, lightdm won't start. The error when I run optimus.sh manually is like this
```
can't open display
can't open display
```
similarly, when running the example acpi calls in intel mode, all methods are failing. Is it because the GPU is not supported yet? only video-nvidia is installed in mhwd, as required in the readme

btw I think it might be better if the readme reminds us to update busID in no-optimus.sh as well in the `DO THIS BEFORE RUNNING INSTALL SCRIPT` part, not just nvidia-xorg.conf, as failing to do so results in system not booting properly for me

**Comment by dglt1** [comment]
sorry for the late reply, been busy these past couple weeks.

> environment: manjaro fresh install

i ran into something this past week and ended up with a flashing screen and no X failing to start using nvidia mode and it ended up being that `xorg-xrandr`  was not installed and so without it, the xrandr commands do nothing and they are needed for nvidia prime mode to work.

i thought xrandr was something that gets installed by mhwd but for some reason, this time it did not.

if that is not your issue, it's almost always due to conflicting video configurations or a service from something like optimus-manager still active. check the following:
- if optimus-manager was previously installed, make sure you removed all of it and disabled any related services being used by it. optimus-manager has a --cleanup option that needs to be run before uninstalling to get rid of any traces of it.

- if you were using bumblebee, do the same and make sure it's actually gone and that bumblebeed.service is disabled
`sudo systemctl disable bumblebeed --now`

- make sure any bbswitch packages are also gone, these will cause you problems.

- check these directories and make sure there are no other conflicting video configurations.
/etc/X11/xorg.conf.d/
/etc/X11/mhwd.d/
/etc/modprobe.d/
/etc/modules-load.d/

when using nvidia mode, the only video configs in those directories should be 99-nvidia.conf  and in intel mode should be 99-intel.conf .  if there are other video configurations in there, get rid of them. **dont delete keyboard and mouse configurations if there are any. just video related .conf files.**

- last but not least, when you edited /etc/lightdm/lightdm.conf are you sure you edited the correct line? i ask this because it's a common and easy mistake to make. there are 2 lines that say 
"display-setup-script=" , the first one is only an example line. the one thats further down towards the bottom of lightdm.conf  is the one you want to uncomment (remove #) and edit to match this

`display-setup-script=/usr/local/bin/optimus.sh`




> similarly, when running the example acpi calls in intel mode, all methods are failing. Is it because the GPU is not supported yet?

apparently the MX nvidia cards will stay powered down on there own if the nvidia modules are not available and it is removed from sysfs which are both done by optimus-switch after editing  no-optimus.sh .  so with an MX card you dont need the acpi call for it to remain off on it's own. others with MX cards have made me aware of this and have done testing with powertop and the nvidia card does in fact remain off while using intel-only mode.

**Comment by salvianreynaldi** [comment]
Thank you for the reply,
I can confirm those 4 directories are clean, and as this is fresh install there's also neither bumblebee nor optimus manager. Meanwhile, `xorg-xrandr` was indeed not installed. I just installed the package. However, I can't try switching to nvidia mode because there's another unrelated issue which hinders recovery attempt using installation media (in case I get flashing screen again), and currently I'm happy with intel mode too. I might test nvidia mode later.
You can close this issue for now

> apparently the MX nvidia cards will stay powered down on there own if the nvidia modules are not available and it is removed from sysfs which are both done by optimus-switch after editing no-optimus.sh . so with an MX card you dont need the acpi call for it to remain off on it's own. others with MX cards have made me aware of this and have done testing with powertop and the nvidia card does in fact remain off while using intel-only mode.

Okay great! Once again, thanks
