### ISSUE TITLE
Troubles with screen suspend/turn off

### ISSUE THREAD

**Issue by clementpoiret** [dglt1/optimus-switch#7]
Hi,

I'm using optimus-switch successfully on Manjaro, and it's perfect. I just have a little problem with screen suspend/turn off.
In intel-only mode, when the screen is turning off, it won't turn back on again, I have to close the lid, wait for the computer to go to sleep and open it again to see lightdm.
Do you know how can I fix that?
Thanks.

**Comment by dglt1** [comment]
> In intel-only mode, when the screen is turning off, it won't turn back on again

just to clarify, your referring to the screen turning off from inactivity, but wont turn on after moving mouse/touchpad or pressing keys?

i've never come across this issue but xorg logs might show whats going on. right after it happens the next time, post the output of these commands to a pastebin and link them here.
```
inxi -Fxxxza --no-host
journalctl -b0 -p3 --no-host
cat /var/log/Xorg.0.log
```

**Comment by clementpoiret** [comment]
Yes, you're right. Here are my logs: https://pastebin.com/faw7UKE8

**Comment by clementpoiret** [comment]
Update: it may not be linked to the screen itself but to lightdm/xfce. If I disable "automatically lock the session" inside power manager, it's working well. Maybe a wrong lightdm.conf?

**Comment by dglt1** [comment]
> If I disable "automatically lock the session" inside power manager, it's working well. Maybe a wrong lightdm.conf?

i cant seem to reproduce this with lightlocker, i use `betterscreenlock` instead of light locker but i tried to reproduce with lightlocker and could not.

as for lightdm.conf, you could take a look and see if anything seems wrong, as of about a week ago editing lightdm.conf to setup optimus-switch is no longer necessary since the installer now creates `/etc/lightdm/lightdm.conf.d/lightdm.conf` with only the `display-setup-script` line in it.
