### ISSUE TITLE
Fully Power Down Discrete GPU

### ISSUE THREAD

**Issue by fdiblen** [dglt1/optimus-switch#8]
Hi,

I am using https://github.com/dglt1/optimus-switch-gdm

I realized that it doesn't power down the nvidia card which reduces the battery life.
Please see:
https://wiki.archlinux.org/index.php/Hybrid_graphics#Fully_Power_Down_Discrete_GPU

It would be very nice too add this as well.

Thanks!

**Comment by dglt1** [comment]
I know the instructions are a bit of a mess, if you read further down you’ll see the instructions that need to be run from intel mode explain which acpi call to use and what lines to edit and uncomment from /etc/switch/intel/no-optimus.sh

The reason I did it this way is for stability rather than using something like bbswitch or nouveau that both come with their own issues (black screen, lockups, etc..).  that said, the scripts are simple so if you wanted to use bbswitch instead of acpi_call you could leave the acpi_call line commented out and instead add “options bbswitch load_state=0” to
/etc/switch/intel/intel-modprobe.conf

You would obviously need bbswitch installed. I’m not suggesting you do this, but it’s an alternative in case acpi_call fails to power down the gpu but I’ve only seen that happen once or twice and the ones where the acpi_call detection script fails to return a “Works!” result.  Some gpu’s don’t need anything other than making sure all nvidia modules are unloaded and power themselves down.



________________________________

**Comment by dglt1** [comment]
> It would be very nice too add this as well.

can you confirm if you did the additional steps to detect the right acpi call and edit/uncomment the lines in `/etc/switch/intel/no-optimus.sh` ?

**Comment by fdiblen** [comment]
Hi,

The method dind't work. My computer was freezing.
Just to let you know that I switched to experimental nvidia drivers which has gpu offloading support. This solved the issue.
